//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturaciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public int Id { get; set; }
        public string tipo_factura { get; set; }
        public string nombre_autor { get; set; }
        public string domicilio_comercial { get; set; }
        public string cuit { get; set; }
        public string leyenda { get; set; }
        public string Numero_factura { get; set; }
        public Nullable<System.DateTime> fecha_inicio_actividad { get; set; }
        public string nombre_comprador { get; set; }
        public Nullable<System.DateTime> fecha_emicion { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento { get; set; }
    }
}
